const abi = [
    {
        inputs: [
            { internalType: 'address', name: '_usdcAddress', type: 'address' },
            { internalType: 'address', name: '_feeTaker', type: 'address' },
            { internalType: 'address', name: '_liquidityPool', type: 'address' },
            { internalType: 'address', name: '_oracle', type: 'address' },
            { internalType: 'address[]', name: '_approveAssets', type: 'address[]' },
            { internalType: 'uint16', name: '_fee', type: 'uint16' },
            { internalType: 'uint16', name: '_leverage', type: 'uint16' },
            { internalType: 'uint16', name: '_minRunTime', type: 'uint16' },
            { internalType: 'uint16', name: '_maxRunTime', type: 'uint16' },
        ],
        stateMutability: 'nonpayable',
        type: 'constructor',
    },
    { inputs: [], name: 'DepositFailed', type: 'error' },
    { inputs: [{ internalType: 'address', name: 'asset', type: 'address' }], name: 'DuplicateAsset', type: 'error' },
    { inputs: [{ internalType: 'uint256', name: 'betId', type: 'uint256' }], name: 'FailedToSettleBet', type: 'error' },
    { inputs: [], name: 'FailedToTakeFee', type: 'error' },
    { inputs: [], name: 'FailedToTakeWager', type: 'error' },
    { inputs: [], name: 'InsufficientAmount', type: 'error' },
    {
        inputs: [
            { internalType: 'uint256', name: 'requested', type: 'uint256' },
            { internalType: 'uint256', name: 'available', type: 'uint256' },
        ],
        name: 'InsufficientPepeBalance',
        type: 'error',
    },
    { inputs: [], name: 'InvalidAddress', type: 'error' },
    { inputs: [], name: 'InvalidAmount', type: 'error' },
    { inputs: [], name: 'InvalidFee', type: 'error' },
    { inputs: [], name: 'InvalidLeverage', type: 'error' },
    { inputs: [], name: 'InvalidTime', type: 'error' },
    { inputs: [], name: 'LiquidityPoolNotSet', type: 'error' },
    { inputs: [], name: 'NotExternalOracle', type: 'error' },
    { inputs: [], name: 'NotOracle', type: 'error' },
    { inputs: [{ internalType: 'address', name: 'asset', type: 'address' }], name: 'UnapprovedAsset', type: 'error' },
    { inputs: [{ internalType: 'uint256', name: 'betId', type: 'uint256' }], name: 'UnelapsedBet', type: 'error' },
    { inputs: [], name: 'WithdrawalFailed', type: 'error' },
    {
        anonymous: false,
        inputs: [
            { indexed: true, internalType: 'uint256', name: 'betId', type: 'uint256' },
            { indexed: true, internalType: 'address', name: 'initiator', type: 'address' },
            { indexed: true, internalType: 'address', name: 'asset', type: 'address' },
            { indexed: false, internalType: 'uint256', name: 'openingPrice', type: 'uint256' },
            { indexed: false, internalType: 'uint256', name: 'startTime', type: 'uint256' },
            { indexed: false, internalType: 'uint256', name: 'endTime', type: 'uint256' },
            { indexed: false, internalType: 'uint256', name: 'runTime', type: 'uint256' },
        ],
        name: 'BetPlaced',
        type: 'event',
    },
    {
        anonymous: false,
        inputs: [
            { indexed: true, internalType: 'address', name: 'depositor', type: 'address' },
            { indexed: false, internalType: 'uint256', name: 'amount', type: 'uint256' },
        ],
        name: 'Deposit',
        type: 'event',
    },
    {
        anonymous: false,
        inputs: [
            { indexed: true, internalType: 'address', name: 'payer', type: 'address' },
            { indexed: true, internalType: 'address', name: 'feeTaker', type: 'address' },
            { indexed: false, internalType: 'uint256', name: 'fee', type: 'uint256' },
        ],
        name: 'FeePaid',
        type: 'event',
    },
    {
        anonymous: false,
        inputs: [
            { indexed: true, internalType: 'address', name: 'oldFeeTaker', type: 'address' },
            { indexed: true, internalType: 'address', name: 'newFeeTaker', type: 'address' },
        ],
        name: 'FeeTakerChanged',
        type: 'event',
    },
    {
        anonymous: false,
        inputs: [
            { indexed: false, internalType: 'uint16', name: 'oldFee', type: 'uint16' },
            { indexed: false, internalType: 'uint16', name: 'newFee', type: 'uint16' },
        ],
        name: 'FeeUpdated',
        type: 'event',
    },
    {
        anonymous: false,
        inputs: [
            { indexed: false, internalType: 'uint16', name: 'oldLeverage', type: 'uint16' },
            { indexed: false, internalType: 'uint16', name: 'newLeverage', type: 'uint16' },
        ],
        name: 'LeverageUpdated',
        type: 'event',
    },
    {
        anonymous: false,
        inputs: [
            { indexed: true, internalType: 'address', name: 'oldPool', type: 'address' },
            { indexed: true, internalType: 'address', name: 'newPool', type: 'address' },
        ],
        name: 'LiquidityPoolUpdated',
        type: 'event',
    },
    {
        anonymous: false,
        inputs: [
            { indexed: false, internalType: 'uint256', name: 'minBetAmount', type: 'uint256' },
            { indexed: false, internalType: 'uint256', name: 'maxBetAmount', type: 'uint256' },
        ],
        name: 'ModifiedBetAmount',
        type: 'event',
    },
    {
        anonymous: false,
        inputs: [
            { indexed: false, internalType: 'uint16', name: 'minRunTime', type: 'uint16' },
            { indexed: false, internalType: 'uint16', name: 'maxRunTime', type: 'uint16' },
        ],
        name: 'ModifiedBetRunTime',
        type: 'event',
    },
    {
        anonymous: false,
        inputs: [{ indexed: false, internalType: 'address[]', name: 'assets', type: 'address[]' }],
        name: 'NewAssets',
        type: 'event',
    },
    {
        anonymous: false,
        inputs: [
            { indexed: true, internalType: 'address', name: 'oldOracle', type: 'address' },
            { indexed: true, internalType: 'address', name: 'newOracle', type: 'address' },
        ],
        name: 'OracleUpdated',
        type: 'event',
    },
    {
        anonymous: false,
        inputs: [{ indexed: false, internalType: 'address', name: 'account', type: 'address' }],
        name: 'Paused',
        type: 'event',
    },
    {
        anonymous: false,
        inputs: [{ indexed: false, internalType: 'address[]', name: 'assets', type: 'address[]' }],
        name: 'RevokedAssets',
        type: 'event',
    },
    {
        anonymous: false,
        inputs: [
            { indexed: true, internalType: 'bytes32', name: 'role', type: 'bytes32' },
            { indexed: true, internalType: 'bytes32', name: 'previousAdminRole', type: 'bytes32' },
            { indexed: true, internalType: 'bytes32', name: 'newAdminRole', type: 'bytes32' },
        ],
        name: 'RoleAdminChanged',
        type: 'event',
    },
    {
        anonymous: false,
        inputs: [
            { indexed: true, internalType: 'bytes32', name: 'role', type: 'bytes32' },
            { indexed: true, internalType: 'address', name: 'account', type: 'address' },
            { indexed: true, internalType: 'address', name: 'sender', type: 'address' },
        ],
        name: 'RoleGranted',
        type: 'event',
    },
    {
        anonymous: false,
        inputs: [
            { indexed: true, internalType: 'bytes32', name: 'role', type: 'bytes32' },
            { indexed: true, internalType: 'address', name: 'account', type: 'address' },
            { indexed: true, internalType: 'address', name: 'sender', type: 'address' },
        ],
        name: 'RoleRevoked',
        type: 'event',
    },
    {
        anonymous: false,
        inputs: [
            { indexed: true, internalType: 'address', name: 'user', type: 'address' },
            { indexed: true, internalType: 'uint256', name: 'betId', type: 'uint256' },
            { indexed: true, internalType: 'bool', name: 'won', type: 'bool' },
            { indexed: false, internalType: 'uint256', name: 'payout', type: 'uint256' },
        ],
        name: 'SettledBet',
        type: 'event',
    },
    {
        anonymous: false,
        inputs: [{ indexed: false, internalType: 'address', name: 'account', type: 'address' }],
        name: 'Unpaused',
        type: 'event',
    },
    {
        anonymous: false,
        inputs: [
            { indexed: true, internalType: 'address', name: 'user', type: 'address' },
            { indexed: false, internalType: 'uint256', name: 'amount', type: 'uint256' },
        ],
        name: 'Withdrawal',
        type: 'event',
    },
    {
        inputs: [],
        name: 'DEFAULT_ADMIN_ROLE',
        outputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [],
        name: 'IUSDC',
        outputs: [{ internalType: 'contract IERC20', name: '', type: 'address' }],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [],
        name: 'PEPE_ADMIN',
        outputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [],
        name: 'PEPE_CROUPIER',
        outputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [{ internalType: 'address[]', name: 'newAssets', type: 'address[]' }],
        name: 'addNewAssets',
        outputs: [],
        stateMutability: 'nonpayable',
        type: 'function',
    },
    {
        inputs: [{ internalType: 'address', name: '', type: 'address' }],
        name: 'approvedAssets',
        outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [{ internalType: 'address', name: '', type: 'address' }],
        name: 'balances',
        outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
        name: 'betDetails',
        outputs: [
            { internalType: 'uint256', name: 'amount', type: 'uint256' },
            { internalType: 'uint256', name: 'wagerAmount', type: 'uint256' },
            { internalType: 'uint256', name: 'openingPrice', type: 'uint256' },
            { internalType: 'uint256', name: 'closingPrice', type: 'uint256' },
            { internalType: 'uint256', name: 'startTime', type: 'uint256' },
            { internalType: 'uint256', name: 'endTime', type: 'uint256' },
            { internalType: 'uint256', name: 'betId', type: 'uint256' },
            { internalType: 'address', name: 'initiator', type: 'address' },
            { internalType: 'address', name: 'asset', type: 'address' },
            { internalType: 'bool', name: 'isLong', type: 'bool' },
            { internalType: 'bool', name: 'active', type: 'bool' },
        ],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [],
        name: 'betId',
        outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [{ internalType: 'uint256', name: 'amount', type: 'uint256' }],
        name: 'deposit',
        outputs: [],
        stateMutability: 'nonpayable',
        type: 'function',
    },
    {
        inputs: [],
        name: 'fee',
        outputs: [{ internalType: 'uint16', name: '', type: 'uint16' }],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [],
        name: 'feeTaker',
        outputs: [{ internalType: 'address', name: '', type: 'address' }],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [{ internalType: 'bytes32', name: 'role', type: 'bytes32' }],
        name: 'getRoleAdmin',
        outputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [
            { internalType: 'bytes32', name: 'role', type: 'bytes32' },
            { internalType: 'address', name: 'account', type: 'address' },
        ],
        name: 'grantRole',
        outputs: [],
        stateMutability: 'nonpayable',
        type: 'function',
    },
    {
        inputs: [
            { internalType: 'bytes32', name: 'role', type: 'bytes32' },
            { internalType: 'address', name: 'account', type: 'address' },
        ],
        name: 'hasRole',
        outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [],
        name: 'leverage',
        outputs: [{ internalType: 'uint16', name: '', type: 'uint16' }],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [],
        name: 'liquidityPool',
        outputs: [{ internalType: 'address', name: '', type: 'address' }],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [],
        name: 'maxBetAmount',
        outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [],
        name: 'maxRunTime',
        outputs: [{ internalType: 'uint16', name: '', type: 'uint16' }],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [],
        name: 'minBetAmount',
        outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [],
        name: 'minRunTime',
        outputs: [{ internalType: 'uint16', name: '', type: 'uint16' }],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [{ internalType: 'uint16', name: 'newFee', type: 'uint16' }],
        name: 'modifyFee',
        outputs: [],
        stateMutability: 'nonpayable',
        type: 'function',
    },
    {
        inputs: [{ internalType: 'uint16', name: 'newLeverage', type: 'uint16' }],
        name: 'modifyLeverage',
        outputs: [],
        stateMutability: 'nonpayable',
        type: 'function',
    },
    {
        inputs: [
            { internalType: 'uint256', name: '_minAmount', type: 'uint256' },
            { internalType: 'uint256', name: '_maxAmount', type: 'uint256' },
        ],
        name: 'modifyMinAndMaxBetAmount',
        outputs: [],
        stateMutability: 'nonpayable',
        type: 'function',
    },
    {
        inputs: [
            { internalType: 'uint16', name: '_minRunTime', type: 'uint16' },
            { internalType: 'uint16', name: '_maxRunTime', type: 'uint16' },
        ],
        name: 'modifyMinAndMaxBetRunTime',
        outputs: [],
        stateMutability: 'nonpayable',
        type: 'function',
    },
    {
        inputs: [],
        name: 'oracle',
        outputs: [{ internalType: 'address', name: '', type: 'address' }],
        stateMutability: 'view',
        type: 'function',
    },
    { inputs: [], name: 'pause', outputs: [], stateMutability: 'nonpayable', type: 'function' },
    {
        inputs: [],
        name: 'paused',
        outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [
            { internalType: 'address', name: 'user', type: 'address' },
            { internalType: 'address', name: 'asset', type: 'address' },
            { internalType: 'uint256', name: 'amount', type: 'uint256' },
            { internalType: 'uint256', name: 'openingPrice', type: 'uint256' },
            { internalType: 'uint256', name: 'runTime', type: 'uint256' },
            { internalType: 'bool', name: 'isLong', type: 'bool' },
        ],
        name: 'placeBet',
        outputs: [],
        stateMutability: 'nonpayable',
        type: 'function',
    },
    {
        inputs: [
            { internalType: 'bytes32', name: 'role', type: 'bytes32' },
            { internalType: 'address', name: 'account', type: 'address' },
        ],
        name: 'renounceRole',
        outputs: [],
        stateMutability: 'nonpayable',
        type: 'function',
    },
    {
        inputs: [
            { internalType: 'bytes32', name: 'role', type: 'bytes32' },
            { internalType: 'address', name: 'account', type: 'address' },
        ],
        name: 'revokeRole',
        outputs: [],
        stateMutability: 'nonpayable',
        type: 'function',
    },
    {
        inputs: [{ internalType: 'address', name: '_liquidityPool', type: 'address' }],
        name: 'setLiquidityPool',
        outputs: [],
        stateMutability: 'nonpayable',
        type: 'function',
    },
    {
        inputs: [
            { internalType: 'uint256', name: 'betID', type: 'uint256' },
            { internalType: 'uint256', name: 'closingPrice', type: 'uint256' },
        ],
        name: 'settleBet',
        outputs: [],
        stateMutability: 'nonpayable',
        type: 'function',
    },
    {
        inputs: [{ internalType: 'bytes4', name: 'interfaceId', type: 'bytes4' }],
        name: 'supportsInterface',
        outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
        stateMutability: 'view',
        type: 'function',
    },
    { inputs: [], name: 'unPause', outputs: [], stateMutability: 'nonpayable', type: 'function' },
    {
        inputs: [{ internalType: 'address[]', name: 'assets', type: 'address[]' }],
        name: 'unapproveAssets',
        outputs: [],
        stateMutability: 'nonpayable',
        type: 'function',
    },
    {
        inputs: [{ internalType: 'address', name: 'newFeeTaker', type: 'address' }],
        name: 'updateFeeTaker',
        outputs: [],
        stateMutability: 'nonpayable',
        type: 'function',
    },
    {
        inputs: [{ internalType: 'address', name: '_oracle', type: 'address' }],
        name: 'updateOracle',
        outputs: [],
        stateMutability: 'nonpayable',
        type: 'function',
    },
    {
        inputs: [{ internalType: 'uint256', name: 'amount', type: 'uint256' }],
        name: 'withdraw',
        outputs: [],
        stateMutability: 'nonpayable',
        type: 'function',
    },
];

export { abi };
